### ISSUE TITLE
New webhook triggers for subscriptions and customers

### ISSUE THREAD

**Issue by mnida** [uselotus/lotus#440]
**Is your feature request related to a problem? Please describe.**
Users want webhooks for these events:
* when a subscription ends/is cancelled
* when a subscription is created
* when a subscription is renewed
* customer created

**Describe the solution you'd like**
In the backend add this webhook functionality using our alerts framework and svix.

In the frontend simply add the checkbox in the create webhook url form.

**Comment by djanda97** [comment]
Hi @mnida!

If this issue is still available, I would like to work on it. After cloning the repo and poking around the codebase for a while, I found a few files that look like a good starting point for adding new webhooks.

Backend:
* https://github.com/uselotus/lotus/blob/main/backend/metering_billing/utils/enums/enums.py#L183
* https://github.com/uselotus/lotus/blob/main/backend/metering_billing/webhooks.py
* https://github.com/uselotus/lotus/blob/main/backend/api/serializers/webhook_serializers.py

Frontend:
* https://github.com/uselotus/lotus/blob/main/frontend/src/components/Settings/settings/tabs/DeveloperTab.tsx

Do you have a recommendation for other files (either backend or frontend) to look into that will be required for adding new webhooks?

Cheers,
David

**Comment by mnida** [comment]
@djanda97 Great! Yep this issue is still available! You should be all set on the frontend side beside that DeveloperTab you pointed out.

Looping in our @diego-escobedo to check if there is anything else on the backend.

**Comment by diego-escobedo** [comment]
Hey David! Sorry for the late response, missed this one. Looks like the right path for the backend. I'll add in a few other things you might find useful. 

- Webhooks need to be registered with the webhooks server (Svix) before being used, here's where we do it in the code: https://github.com/uselotus/lotus/blob/335b69d17b032d3849f56c893282177ccc1d5fc9/backend/lotus/settings.py#L665 Should be pretty plug and play
- https://raw.githubusercontent.com/uselotus/lotus/442db21387ebaf47c65d6bf2fdb569d12abcd97d/docs/webhooks/webhooks.mdx the current documentation page we have for webhooks. Unfortunately, we don't have a great way of displaying the schema for the response objects in our mintlify docs atm, so what we do i: Run management command `python manage.py generate_schema`, copy paste the openapi spec into a different openapi renderer, and screenshot it. In the case of an existing response schema (like we have for invoices), we just link them to the appropriate place in the docs. 

In terms of where you'd actually be putting the `x_webhook()` calls imported from the webhooks file:
- Subscriptions ending / being cancelled happen mostly at: https://github.com/uselotus/lotus/blob/335b69d17b032d3849f56c893282177ccc1d5fc9/backend/api/views.py#L468 in teh add/update/cancel custom actions.
- Subscription renewal happens at https://github.com/uselotus/lotus/blob/335b69d17b032d3849f56c893282177ccc1d5fc9/backend/metering_billing/invoice.py#L254 . Notice how we make is_new false automatically.
- Customer creation happens at https://github.com/uselotus/lotus/blob/335b69d17b032d3849f56c893282177ccc1d5fc9/backend/api/views.py#L212 . 

Doing all of the webhooks at once might be too much to chew off / review in a single PR, so perhaps spinning them out one issue at a time might end up being easier. 

Let me know if you need any more details or if you're curious about how the webhooks work in more detail! Happy to discuss.

**Comment by djanda97** [comment]
Thanks for the info! I agree that trying to implement all the new webhooks would be a bit much to tackle in a single PR, so I'll start with the customer created webhook & reach out when I have any questions after diving into the code!

**Comment by mnida** [comment]
Hey @djanda97 checking in to see how the issue is going?

**Comment by djanda97** [comment]
Hi @mnida, so far so good! I've created a draft PR that registers the customer created webhook with the webhook server (svix) and adds it to the `WEBHOOK_TRIGGER_EVENTS` class. The bulk of the implementation is something I plan to get to this upcoming week.

**Comment by mnida** [comment]
Great! Awesome to hear and excited to review next week.

**Comment by djanda97** [comment]
> **Is your feature request related to a problem? Please describe.** Users want webhooks for these events:
> 
>     * when a subscription ends/is cancelled
> 
>     * when a subscription is created
> 
>     * when a subscription is renewed
> 
>     * customer created
> 
> 
> **Describe the solution you'd like** In the backend add this webhook functionality using our alerts framework and svix.
> 
> In the frontend simply add the checkbox in the create webhook url form.

Now that #539 is merged, could the subscription related webhooks be split up into different issues so that they could be worked on individually? I would be interested in implementing a few more now that I've done it once before and know the general locations where code would need to be added :smile:

**Comment by mnida** [comment]
Yeah! @djanda97 Feel free to create some more issues, we treated this one as just customer-created. You can use the same issue format and create and self-assign to as many as you are up for!
